added echo of error and exit if failed

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -59,10 +59,10 @@ jobs:
 
             status=$(aws ssm list-commands --command-id $command_id --query "Commands[0].StatusDetails" --output text)
 
-            echo "$status"
-
             if [ "$status" == "Success" ]; then
               echo "Command executed successfully"
             else
               echo "Command failed"
+              echo "Error: $status"
+              exit 1
             fi
